### ISSUE TITLE
Unable to install: ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by lynaghk** [RelationalAI/rai-sdk-python#1]
![Screen Shot 2021-08-25 at 11 46 47 AM](https://user-images.githubusercontent.com/147919/130847841-bf6846d1-f5ee-4f7d-8358-9d4517cf593b.png)
```
📡🏠 | git rev-parse HEAD                                                                                                               11:44:05
f505106d028c5e1ee0543f9f2ecaebe7629de241
📡🏠 | python --version                                                                                                                 11:44:37
Python 3.9.5
📡🏠 | python setup.py install --user                                                                                                   11:44:41
running install
running bdist_egg
running egg_info
writing rai_sdk.egg-info/PKG-INFO
writing dependency_links to rai_sdk.egg-info/dependency_links.txt
writing requirements to rai_sdk.egg-info/requires.txt
writing top-level names to rai_sdk.egg-info/top_level.txt
reading manifest file 'rai_sdk.egg-info/SOURCES.txt'
writing manifest file 'rai_sdk.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11.3-arm64/egg
running install_lib
running build_py
copying rai_sdk.egg-info/PKG-INFO -> build/bdist.macosx-11.3-arm64/egg/EGG-INFO
copying rai_sdk.egg-info/SOURCES.txt -> build/bdist.macosx-11.3-arm64/egg/EGG-INFO
copying rai_sdk.egg-info/dependency_links.txt -> build/bdist.macosx-11.3-arm64/egg/EGG-INFO
copying rai_sdk.egg-info/requires.txt -> build/bdist.macosx-11.3-arm64/egg/EGG-INFO
copying rai_sdk.egg-info/top_level.txt -> build/bdist.macosx-11.3-arm64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/Users/dev/work/relational-ai/kevin-rai/rai-sdk-python/setup.py", line 21, in <module>
    setup(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Users/dev/Library/Python/3.9/lib/python/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-3286](https://relationalai.atlassian.net/browse/RAI-3286).

_This link is only accessible to employees of RelationalAI._
