### ISSUE TITLE
`show.problems` error

### ISSUE THREAD

**Issue by Ally-R** [RelationalAI/rai-sdk-python#99]
Python SDK: `show.problems` is erroring with this message:
```
Traceback (most recent call last):
  File "run-tests.py", line 187, in <module>
    res = run_tests(database, engine, command, dataset, args.verbose, start_time)
  File "run-tests.py", line 129, in run_tests
    show.problems(tst_res) # Print errors
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/railib/show.py", line 83, in problems
    problems = rsp.get("problems", None)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by larf311** [comment]
That function appears to expect a dictionary and instead it's being given a list. Where does `tst_res` come from?

**Comment by Ally-R** [comment]
`tst_res` is just the result of an `exec` call. This used to be a `query` call, and `show.problems` worked on that. It broke when I tried to update to the latest SDK version, I think because the output type changed from `dict` to `list`, and it seems `show.problems` hasn't been updated?
Here's the full definition: `tst_res = api.exec(ctx, database, engine, command, readonly=True)`

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6611](https://relationalai.atlassian.net/browse/RAI-6611).

_This link is only accessible to employees of RelationalAI._
